config/routes.rb
OneClickOrgs::Application.routes.draw do

  resource :constitution
  resource :constitution_proposal_bundles

  get '/timeline' => 'one_click#timeline', :as => 'timeline'

  post '/votes/vote_for/:id' => 'votes#vote_for', :as => 'vote_for'
  post '/votes/vote_against/:id' => 'votes#vote_against', :as => 'vote_against'

  resources :decisions

  resources :proposals do
    member do
      put :open
    end

    resources :comments
  end
  
  resources :add_member_proposals
  resources :eject_member_proposals
  resources :change_member_class_proposals
  resources :found_association_proposals

  resources :resolution_proposals do
    member do
      get :support
      put :pass
      put :pass_to_meeting
    end

    resources :comments
  end

  resources :resolutions do
    resources :comments
  end
  resources :generic_resolutions
  resources :change_meeting_notice_period_resolutions
  resources :change_quorum_resolutions
  resources :change_name_resolutions
  resources :change_registered_office_address_resolutions
  resources :change_objectives_resolutions
  resources :change_membership_criteria_resolutions
  resources :change_board_composition_resolutions
  resources :change_single_shareholding_resolutions
  resources :change_common_ownership_resolutions

  resources :board_resolutions

  resources :members do
    member do
      get :confirm_eject
      put :eject

      patch :confirm_resign
      patch :resign

      put :induct
    end

    collection do
      get :created
      get :resigned
    end
  end

  resources :founding_members

  resources :founder_members

  resources :directors do
    member do
      post :stand_down
    end
  end

  resources :directorships do
    new do
      get :external
    end
  end

  resources :officerships
  resources :offices

  resources :elections do
    resources :ballots
  end

  get '/one_click(/:action)' => 'one_click'

  get '/login' => 'member_sessions#new', :as => 'login'
  get '/logout' => 'member_sessions#destroy', :as => 'logout'
  resource :member_session, :only => [:new, :create, :destroy]

  get '/admin/login' => 'administrator_sessions#new', :as => 'admin_login'
  get '/admin/logout' => 'administrator_sessions#destroy', :as => 'admin_logout'
  resource :administrator_session, :only => [:new, :create, :destroy]

  match '/welcome(/:action)' => 'welcome', :via => [:get, :post]

  match '/setup(/:action)' => 'setup', :via => [:get, :post]

  resources :organisations
  resources :associations
  resources :companies
  resources :coops do
    collection do
      get :intro
      get :terms
    end
    member do
      put :propose
    end
  end

  resources :meetings do
    resources :comments
  end
  resources :general_meetings
  resources :annual_general_meetings
  resources :board_meetings
  resources :minutes

  resources :shares do
    collection do
      get :edit_share_value
      put :update_share_value

      get :edit_minimum_shareholding
      put :update_minimum_shareholding

      get :edit_interest_rate
      put :update_interest_rate
    end
  end
  resources :share_transactions do
    member do
      get :confirm_approve
      put :approve
    end
  end
  resources :share_applications
  resources :share_withdrawals

  resource :membership_application_form

  resource :registration_form

  resource :board

  resources :tasks do
    member do
      put :dismiss
    end
  end

  resources :documents

  get '/admin' => 'admin#index'

  namespace :admin do
    resources :coops do
      member do
        put :found
      end

      resources :documents
    end

    resources :constitutions
    resources :registration_forms
    resources :members
  end

  get '/i/:id' => 'invitations#edit', :as => 'short_invitation'
  resources :invitations

  get '/r/:id' => 'password_resets#edit', :as => 'short_password_reset'
  resources :password_resets

  post '/system/test_email' => 'system#test_email'
  get '/system/test_exception_notification' => 'system#test_exception_notification'

  get '/checklist' => 'one_click#checklist', :as => 'checklist'

  root :to => 'one_click#dashboard'
end

app/views/shared/_propose_new_member_form.html.haml
- if can?(:create, FoundingMember)
  %h3
    Invite another Founding Member
  %p
    = form_for(@new_member, :as => :member, :url => { :controller => :members, :action => :create_founding_member }) do |f|
      %p
        = f.label(:email, "Email Address")
        = f.email_field :email
      %p
        = f.label(:first_name)
        = f.text_field :first_name
      %p
        = f.label(:last_name)
        = f.text_field :last_name
      -# Cf. issue #146: don't display member class form
        = f.hidden_field :member_class_id
      -# - if co.member_classes.count == 1
      -#   = f.hidden_field :member_class_id
      -# - else
      -#   %p
      -#     = f.label(:class)
      -#     = f.collection_select(:member_class_id, co.member_classes.to_a, :id, :name)
      %p
        = submit_tag "Send invitation", :id => 'submit'
- elsif can?(:create, AddMemberProposal)
  %h3
    Propose a new member
  %p
    = form_for(@new_member, :as => :member, :url => members_path) do |f|
      %p
        = f.label(:email, "Email address")
        = f.email_field :email
      %p
        = f.label(:first_name)
        = f.text_field :first_name
      %p
        = f.label(:last_name)
        = f.text_field :last_name
      - if co.member_classes.count == 1
        = f.hidden_field :member_class_id
      - else
        %p
          = f.label(:class)
          = f.collection_select(:member_class_id, co.member_classes.to_a, :id, :name)
      %p
        = submit_tag "Invite member", :id => 'submit'

app/views/shared/_start_founding_vote_confirmation.html.haml
%h3
  Ready to start the Founding Vote.
  
%p
  Clicking the Confirm button will send an email to all the Founding Members proposing to create an Association with the constitution in its present form. Everyone will have 3 days to vote (this is a fixed period of time, separate from the voting period in your constitution). You'll be able to keep track of who's voted on the Founding Members page. If 3 or more people vote to form the Association a legal structure will be created. Making any changes after this point will require a vote of the members.

%p#loading
  = image_tag('squares-loading.gif', :alt => 'Loading')
  %span Starting the founding vote

%p
  %button#cancel_start_founding_vote Cancel
  %button#confirm_start_founding_vote Confirm